### ISSUE TITLE
Assertion error while creating mock phenotype group example for TensorQTL SQTL application

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#302]
After grouping the MWE phenotype_df with "A", "B", "C" 
The following error occurs.

```
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/home/hs3163/miniconda3/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/hs3163/miniconda3/lib/python3.9/site-packages/tensorqtl/genotypeio.py", line 40, in run
    for item in self.generator:
  File "/home/hs3163/miniconda3/lib/python3.9/site-packages/tensorqtl/genotypeio.py", line 451, in generate_data
    assert np.all([self.cis_ranges[g.index[0]][0] == self.cis_ranges[i][0] and self.cis_ranges[g.index[0]][1] == self.cis_ranges[i][1] for i in g.index[1:]])
AssertionError
```

However, removing the group ( `gourp_s = group_s`) option, the function run perfectly fine.

The cis.map_norminal function run perfectly fine with the group ( `gourp_s = group_s`) option.

**Comment by hsun3163** [comment]
By introducing the group_s, map_cis will invoke a process to check whether all phenotypes within a group must have the same number of SNPs, which is not the case in the our data, as shown below:
```
{'CHL1': array([   0, 5603]),
 'CHL1-AS2': array([   0, 5604]),
 'LINC01266': array([   0, 8258]),
 'CNTN6': array([  335, 12194]),
 'CNTN4': array([ 5003, 18193]),
 'TRNT1': array([12449, 23961]),
 'CRBN': array([12737, 24231]),
 'AC034195.1': array([15246, 26419]),
 'LRRN1': array([16449, 27225])}
```
This is due to the fact that snps are not uniformly distributed across the genome.

However, it is still needed to investigate why the phenotype group generated by the GTEX method doesn't have this problem.
