### ISSUE TITLE
Error in sumstat_standardization step (summary_stats_standardizer.ipynb)

### ISSUE THREAD

**Issue by Travyse** [cumc/xqtl-pipeline#353]
I receive the following error when running the `sumstat_standardization` step in the summary_stats_standardizer.ipynb notebook.
```
Traceback (most recent call last):
  File "/sc/arion/projects/load/users/edwart10/projects/xQTL-STARNET-Analysis-05-24-2022/QTL-Association-Testing/cisQTL-Analysis-Workflows/TensorQTL-QTL-Association-Testing/tmplpgblv4s/singularity_run_49211.py", line 34, in <module>
    subject = check_indels(read_sumstat(target_dict,None,True)[["CHR","POS","SNP","A0","A1"]])
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/indexing.py", line 1316, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['SNP'] not in index"
```

I looked into the code, and it seems like this error stems from the `read_sumstat` function in cugg. "SNP" isn't included in the index of the returned sumstats data frame.

```
if "GENE" in sumstats.columns.values():
        sumstats.index = namebyordA0_A1(sumstats[["GENE","CHR","POS","A0","A1"]],cols=["GENE","CHR","POS","A0","A1"])
    else:
        sumstats.index = namebyordA0_A1(sumstats[["CHR","POS","A0","A1"]],cols=["CHR","POS","A0","A1"])
```

**Comment by hsun3163** [comment]
Hi Travyse, a lot of these issue is due to the outdated version of CUGG, I will let you know when the CUGG and the container is updated.

**Comment by hsun3163** [comment]
cugg updated
