### ISSUE TITLE
"Sequence dictionaries are not the same size" Error in Picard

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#357]
When shrishtee was running RNA_Calling module, at the step of Picard QC,  the following error occurs:
```
INFO    2022-08-22 10:59:12 ProcessExecutor [1] "Checking if R is installed"
10:59:12.543 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/picard-tools/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Mon Aug 22 10:59:12 UTC 2022] CollectMultipleMetrics --INPUT /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/batch_2/SM-AYOSS.Aligned.sortedByCoord.out.bam --OUTPUT /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/batch_2/SM-AYOSS --PROGRAM CollectAlignmentSummaryMetrics --PROGRAM CollectBaseDistributionByCycle --PROGRAM CollectInsertSizeMetrics --PROGRAM MeanQualityByCycle --PROGRAM QualityScoreDistribution --PROGRAM CollectGcBiasMetrics --VALIDATION_STRINGENCY STRICT --REFERENCE_SEQUENCE /restricted/projectnb/casa/skandoi/reference_data/GRCh38_full_analysis_set_plus_decoy_hla.noALT_noHLA_noDecoy_ERCC.fasta --ASSUME_SORTED true --STOP_AFTER 0 --METRIC_ACCUMULATION_LEVEL ALL_READS --INCLUDE_UNPAIRED false --VERBOSITY INFO --QUIET false --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Mon Aug 22 10:59:12 UTC 2022] Executing as skandoi@scc-gg2 on Linux 3.10.0-1160.71.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 11.0.15+10-Ubuntu-0ubuntu0.20.04.1; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: Version:2.25.0
[Mon Aug 22 10:59:12 UTC 2022] picard.analysis.CollectMultipleMetrics done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2151677952
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequence dictionaries are not the same size (195, 287)
    at htsjdk.samtools.util.SequenceUtil.assertSequenceListsEqual(SequenceUtil.java:259)
    at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:342)
    at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:328)
    at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:117)
    at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:739)
    at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
    at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
    at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```

particularly

```
 htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequence dictionaries are not the same size (195, 287)
```

**Comment by hsun3163** [comment]
Some hints toward this issue are:
https://github.com/broadinstitute/picard/issues/126
https://sourceforge.net/p/samtools/mailman/message/26855404/
https://www.seqanswers.com/forum/bioinformatics/bioinformatics-aa/7437-problem-with-qc-metrics#post147263
https://www.biostars.org/p/9483350/

**Comment by hsun3163** [comment]
The actual picard command ran is as followed:
```
java -jar -Xmx6G /opt/picard-tools/picard.jar CollectMultipleMetrics \
    -REFERENCE_SEQUENCE /restricted/projectnb/casa/skandoi/reference_data/GRCh38_full_analysis_set_plus_decoy_hla.noALT_noHLA_noDecoy_ERCC.fasta \
    -PROGRAM CollectAlignmentSummaryMetrics \
    -PROGRAM CollectInsertSizeMetrics \
    -PROGRAM QualityScoreDistribution \
    -PROGRAM MeanQualityByCycle \
    -PROGRAM CollectBaseDistributionByCycle \
    -PROGRAM CollectGcBiasMetrics \
    -VALIDATION_STRINGENCY STRICT \
    -INPUT  /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/batch_2/SM-AYOSS.Aligned.sortedByCoord.out.bam \
    -OUTPUT  /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/batch_2/SM-AYOSS
```

**Comment by hsun3163** [comment]
After testing with the correct fasta reference file,
```
/restricted/projectnb/casa/skandoi/reference_data/GRCh38_full_analysis_set_plus_decoy_hla.noALT_noHLA_noDecoy.fasta
```
instead of
```
/restricted/projectnb/casa/skandoi/reference_data/GRCh38_full_analysis_set_plus_decoy_hla.noALT_noHLA_noDecoy_ERCC.fasta
```
the problem disappears.

The first file is what actually was used to generate the STAR index.
