### ISSUE TITLE
rnaseqc_call_1 error

### ISSUE THREAD

**Issue by Shrishtee-kandoi** [cumc/xqtl-pipeline#373]
The rnaseqc_calling step is giving this error. The std.err files are attached below.. It does look like it ran successfully looking at the error files. 

This is for batch 2 (252) samples out of which only 209 have `*out.md.bam` files..

```
Data is likely RF/fr-firststrand
Using strand specified in the input samples list ['rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf', 'rf'], replacing strand_missing with detected strand
[91mERROR[0m: [91m[rnaseqc_call_1]: [tae5b45401f4f8121]: Executing script in Singularity returns an error (exitcode=1, stderr=/restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/rnaseqc_call/batch_2/1045-DLPFC.Aligned.sortedByCoord.md.stderr).
The script has been saved to /usr4/bf527/skandoi/.sos/f62e6760de9b87f7//usr4/bf527/skandoi/.sos/f62e6760de9b87f7.To reproduce the error please run:
[0m[32msingularity exec  /restricted/projectnb/casa/xqtl-pipeline/container/singularity/rna_quantification.sif /bin/bash /usr4/bf527/skandoi/.sos/f62e6760de9b87f7/singularity_run_42818.sh[0m[91m
[tb4919fae6b9670e0]: Executing script in Singularity returns an error (exitcode=1, stderr=/restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/rnaseqc_call/batch_2/1046-DLPFC.Aligned.sortedByCoord.md.stderr).
The script has been saved to /usr4/bf527/skandoi/.sos/f62e6760de9b87f7//usr4/bf527/skandoi/.sos/f62e6760de9b87f7.To reproduce the error please run:
[0m[32msingularity exec  /restricted/projectnb/casa/xqtl-pipeline/container/singularity/rna_quantification.sif /bin/bash /usr4/bf527/skandoi/.sos/f62e6760de9b87f7/singularity_run_2960.sh[0m[91m
[rnaseqc_call]: Exits with 4 pending steps (rnaseqc_call_2, rnaseqc_call_3, rnaseqc_call_4, rnaseqc_call_5)[0m
```

[1045-DLPFC.Aligned.sortedByCoord.md.stderr.txt](https://github.com/cumc/xqtl-pipeline/files/9462026/1045-DLPFC.Aligned.sortedByCoord.md.stderr.txt)
[1046-DLPFC.Aligned.sortedByCoord.md.stderr.txt](https://github.com/cumc/xqtl-pipeline/files/9462028/1046-DLPFC.Aligned.sortedByCoord.md.stderr.txt)

**Comment by hsun3163** [comment]
Based on the extracted error msg, the nature of this error is `Caused by: java.io.IOException: Stale file handle` which cause `Suppressed: htsjdk.samtools.util.RuntimeIOException: Write error; BinaryCodec in writemode; streamed file (filename not available)`

However it is unclear why only these two samples are expericing this error. Ggl search yeld nothing useful for now. Rerun ongoing to see if the error can be reproduced.

```
NFO	2022-08-29 18:33:21	MarkDuplicates	Written    70,000,000 records.  Elapsed time: 00:09:39s.  Time for last 10,000,000:   78s.  Last read position: chr21:8,255,099
INFO	2022-08-29 18:34:35	MarkDuplicates	Written    80,000,000 records.  Elapsed time: 00:10:53s.  Time for last 10,000,000:   73s.  Last read position: chr21:8,445,808
[Mon Aug 29 18:35:03 UTC 2022] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 20.07 minutes.
Runtime.totalMemory()=2761949184
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Exception when processing alignment for BAM index C9DMAANXX160624:7:1301:15234:21928 2/2 101b aligned to chrX:54444971-54445071.
	at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:141)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:185)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:425)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
	Suppressed: htsjdk.samtools.util.RuntimeIOException: Write error; BinaryCodec in writemode; streamed file (filename not available)
		at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:222)
		at htsjdk.samtools.util.BlockCompressedOutputStream.writeGzipBlock(BlockCompressedOutputStream.java:444)
		at htsjdk.samtools.util.BlockCompressedOutputStream.deflateBlock(BlockCompressedOutputStream.java:408)
		at htsjdk.samtools.util.BlockCompressedOutputStream.flush(BlockCompressedOutputStream.java:321)
		at htsjdk.samtools.util.BinaryCodec.close(BinaryCodec.java:613)
		at htsjdk.samtools.BAMFileWriter.finish(BAMFileWriter.java:155)
		at htsjdk.samtools.SAMFileWriterImpl.close(SAMFileWriterImpl.java:220)
		at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:442)
		... 3 more
	Caused by: java.io.IOException: Stale file handle
		at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
		at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
		at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
		at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
		at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280)
		at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
		at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)
		at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
		at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
		at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
		at htsjdk.samtools.util.Md5CalculatingOutputStream.write(Md5CalculatingOutputStream.java:89)
		at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:220)
		... 10 more
```

**Comment by Shrishtee-kandoi** [comment]
Also, upon running the rnaseqc_call again.. in the STAR_alignment step, Its re-running the jobs or submitting new ones:

```
INFO: Step [32mSTAR_align_1[0m (index=251) is [32mignored[0m with signature constructed
INFO: t88c1bff9b1cb637c [32mre-execute completed[0m
INFO: t88c1bff9b1cb637c [32msubmitted[0m to neurology with job id Your job 7020355 ("job_t88c1bff9b1cb637c") has been submitted
INFO: Waiting for the completion of [32m1[0m task.
INFO: Waiting for the completion of [32m1[0m task.
INFO: Waiting for the completion of [32m1[0m task.
INFO: Waiting for the completion of [32m1[0m task.
INFO: Waiting for the completion of [32m1[0m task.
INFO: Waiting for the completion of [32m1[0m task.
INFO: Waiting for the completion of [32m1[0m task.
INFO: Waiting for the completion of [32m1[0m task.
INFO: Waiting for the completion of [32m1[0m task.
INFO: Waiting for the completion of [32m1[0m task.
```
But when I was running it earlier, it just skipped the STAR_align step and went on to the strand_detected_1 part:

```
INFO: Step [32mSTAR_align_1[0m (index=248) is [32mignored[0m with signature constructed
INFO: Step [32mSTAR_align_1[0m (index=251) is [32mignored[0m with signature constructed
INFO: [32mSTAR_align_1[0m output:   [32m/restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/rnaseqc_call/batch_2/1000-DLPFC.Aligned.sortedByCoord.out.bam /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/rnaseqc_call/batch_2/1000-DLPFC.Aligned.toTranscriptome.out.bam... (504 items in 252 groups)[0m
INFO: Running [32mstrand_detected_1[0m: 
INFO: [32mstrand_detected_1[0m (index=0) is [32mcompleted[0m.
INFO: [32mstrand_detected_1[0m (index=1) is [32mcompleted[0m.
INFO: [32mstrand_detected_1[0m (index=2) is [32mcompleted[0m.
INFO: [32mstrand_detect
```
I'm experiencing the same issue with batch 1 too.

**Comment by hsun3163** [comment]
This is actually a separated issue,

> Also, upon running the rnaseqc_call again.. in the STAR_alignment step, Its re-running the jobs or submitting new ones:
> 
> ```
> INFO: Step [32mSTAR_align_1[0m (index=251) is [32mignored[0m with signature constructed
> INFO: t88c1bff9b1cb637c [32mre-execute completed[0m
> INFO: t88c1bff9b1cb637c [32msubmitted[0m to neurology with job id Your job 7020355 ("job_t88c1bff9b1cb637c") has been submitted
> INFO: Waiting for the completion of [32m1[0m task.
> INFO: Waiting for the completion of [32m1[0m task.
> INFO: Waiting for the completion of [32m1[0m task.
> INFO: Waiting for the completion of [32m1[0m task.
> INFO: Waiting for the completion of [32m1[0m task.
> INFO: Waiting for the completion of [32m1[0m task.
> INFO: Waiting for the completion of [32m1[0m task.
> INFO: Waiting for the completion of [32m1[0m task.
> INFO: Waiting for the completion of [32m1[0m task.
> INFO: Waiting for the completion of [32m1[0m task.
> ```
> 
> But when I was running it earlier, it just skipped the STAR_align step and went on to the strand_detected_1 part:
> 
> ```
> INFO: Step [32mSTAR_align_1[0m (index=248) is [32mignored[0m with signature constructed
> INFO: Step [32mSTAR_align_1[0m (index=251) is [32mignored[0m with signature constructed
> INFO: [32mSTAR_align_1[0m output:   [32m/restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/rnaseqc_call/batch_2/1000-DLPFC.Aligned.sortedByCoord.out.bam /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/rnaseqc_call/batch_2/1000-DLPFC.Aligned.toTranscriptome.out.bam... (504 items in 252 groups)[0m
> INFO: Running [32mstrand_detected_1[0m: 
> INFO: [32mstrand_detected_1[0m (index=0) is [32mcompleted[0m.
> INFO: [32mstrand_detected_1[0m (index=1) is [32mcompleted[0m.
> INFO: [32mstrand_detected_1[0m (index=2) is [32mcompleted[0m.
> INFO: [32mstrand_detect
> ```
> 
> I'm experiencing the same issue with batch 1 too.

This is actually a separated issue, it seems for one sample the signature is missing for STAR align 1. Do you know which sample is it?

**Comment by hsun3163** [comment]
After the rerun mentioned in #378 , the two were ran successfully.

```
1045-DLPFC.Aligned.sortedByCoord.out.bam.zapped
1046-DLPFC.Aligned.sortedByCoord.out.bam.zapped
1045-DLPFC.Aligned.sortedByCoord.out.md.bam      
1046-DLPFC.Aligned.sortedByCoord.out.md.bam
```
