### ISSUE TITLE
sumstat_standarizer fail for chrom 1-20 of haQTL data 

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#424]
following error msg was given:
```
/home/hs3163/miniconda3/lib/python3.9/site-packages/cugg/utils.py:27: UserWarning: There are SNPs 186: REF:ALT = ALT:REF. They will be removed.
  warnings.warn("There are SNPs {}: REF:ALT = ALT:REF. They will be removed.".format(sum(indels)))
Traceback (most recent call last):
  File "/tmp/2874532.1.csg.q/tmp8opss8ac.py", line 49, in <module>
    nq,_ = snps_match(query,subject,keep_ambiguous)
  File "/home/hs3163/miniconda3/lib/python3.9/site-packages/cugg/utils.py", line 254, in snps_match
    new_query, new_subject=snps_match_dup(query,subject,keep_ambiguous)
  File "/home/hs3163/miniconda3/lib/python3.9/site-packages/cugg/utils.py", line 265, in snps_match_dup
    new_query.loc[list(pm.flip) , "STAT"] = -new_query.STAT[list(pm.flip)]
  File "/home/hs3163/miniconda3/lib/python3.9/site-packages/pandas/core/series.py", line 981, in __getitem__
    key = check_bool_indexer(self.index, key)
  File "/home/hs3163/miniconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 2388, in check_bool_indexer
    return check_array_indexer(index, result)
  File "/home/hs3163/miniconda3/lib/python3.9/site-packages/pandas/core/indexers/utils.py", line 579, in check_array_indexer
    raise IndexError(
IndexError: Boolean index has wrong length: 19663378 instead of 19671588
```
Exact reason under investigation

**Comment by hsun3163** [comment]
couple thing that is strange:
1. chrom 22 and 21 works
2. all chrome works on the methylation data

**Comment by hsun3163** [comment]
OK it has to do with why the analysis is not done on a `per gene` basis. As the GWAS comparison routine is called instead of the TWAS one

**Comment by hsun3163** [comment]
The mechanism is changed into
```
len(query.index[0].split(':')) > 3
```
since chr:pos_ref:alt.split(":") = 3, anything beyond that has gene component.
